resources:
  - name: gitrepo_res
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: github-int
      branches:
        except: "*test"
        only: "master*"
      tags:
        except: none
        only: none   
      buildOnCommit: true
      buildOnPullRequest: false
      buildOnPullRequestClose: false
      buildOnRelease: true
      buildOnTagPush: false
      buildOnFileCommit: "*test"
      shallowDepth: 2
      gitConfig: 
        - dont_know
        - dont_know_2
    initialVersion:
      sha: master

   - name: file_res
     type: file
     fileUrl: text.js
     configuration:
        integrationName: docker-int
     initialVersion:
       fileName: test
       fileDtTm: test
    
   - name: image_res
     type: image
     imageName: "library/nginx"
     configuration:
       integrationName: docker-int
     initialVersion:
       imageTag: latest
       
   - name: state_res
     type: state

pipelines:
  - name: pipe_1
    setup:
      runtime: onHost
    steps:
      - name: step1_A
        type: runSh
        setup:
          runtime: onHost
        requires:
          integrations:
            - docker-int
          resources:
            - image_res
            - file_res
        triggeredBy:
          resources:
            - gitrepo_res 
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
          - state_res

      - name: step1_B
        type: runSh
        setup:
          runtime: onHost
        triggeredBy:
          step:
            - state_res 
        execution:
          onExecute:
            - echo "executing..."
