resources:
  - name: gitrepo_res
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: github-int
      branches:
        except: random
    initialVersion:
      sha: master

  - name: file_res
    type: file
    fileUrl: https://github.com/ankul-shippable/sample_java/blob/master/shippable.yml
    configuration:
      integrationName: github-int
    initialVersion:
      fileName: shippable.yml
      fileDtTm: random_value

pipelines:
  - name: pipe_1
    setup:
      runtime: onHost
    steps:
      - name: step1_A
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          runtime: onHost
        triggeredBy:
          resources:
            - gitrepo_res 
        execution:
          onExecute:
            - echo "executing step1_A..."
        outputResources:
          - file_res

      - name: step1_B
        type: bash
        configuration:
          affinityGroup: test_group      
        setup:
          runtime: onHost
        triggeredBy:
          steps:
            - step1_A
        execution:
          onExecute:
            - echo "executing step1_B..."
            
      - name: step1_C
        type: bash
        configuration:
          affinityGroup: test_group      
        setup:
          runtime: onHost
        triggeredBy:
          steps:
            - step1_A
        execution:
          onExecute:
            - echo "executing step1_C..."           

      - name: step1_D
        type: bash
        configuration:
          affinityGroup: test_group      
        setup:
          runtime: onHost
        triggeredBy:
          resources:
            - file_res 
        execution:
          onExecute:
            - echo "executing step1_D..."

      - name: step1_E
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          runtime: onHost
        triggeredBy:
          resources:
            - gitrepo_res 
        execution:
          onExecute:
            - echo "executing step1_E..."

      - name: step1_F
        type: bash
        configuration:
          affinityGroup: test_group      
        setup:
          runtime: onHost
        triggeredBy:
          steps:
            - step1_E 
        execution:
          onExecute:
            - echo "executing step1_F..."
            
            
  - name: pipe_2
    setup:
      runtime: onHost
    steps:
      - name: step2_A
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          runtime: onHost
        triggeredBy:
          resources:
            - gitrepo_res 
        execution:
          onExecute:
            - echo "executing step2_A..."  
            
      - name: step2_B
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          runtime: onHost
        triggeredBy:
          steps:
            - step2_A 
        execution:
          onExecute:
            - echo "executing step2_B..."              
